apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gratibot
  description: Slackbot used to encourage recognition of team accomplishments
  annotations:
  tags:
    - javascript
    - botkit
spec:
  type: chatbot
  lifecycle: production
  owner: liatrio.com
